const INITIAL_VELOCITY = 1;
const INCREASE_VELOCITY = 0.01;
const INITIAL_POSITION = 50;
const FRAME_RATE = 40;

export {
    INITIAL_VELOCITY,
    INCREASE_VELOCITY,
    INITIAL_POSITION,
    FRAME_RATE
}